/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the \"License\");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an \"AS IS\" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: /usr/src/github.com/ROCm/device-metrics-exporter/pkg/amdgpu//gen/amdgpu/ual_grpc.pb.go
//
// Generated by this command:
//
//	mockgen --destination=/usr/src/github.com/ROCm/device-metrics-exporter/pkg/amdgpu/mock_gen/mock_ual.go -package=mock_gen --source=/usr/src/github.com/ROCm/device-metrics-exporter/pkg/amdgpu//gen/amdgpu/ual_grpc.pb.go
//

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"

	amdgpu "github.com/ROCm/device-metrics-exporter/pkg/amdgpu/gen/amdgpu"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockUALSvcClient is a mock of UALSvcClient interface.
type MockUALSvcClient struct {
	ctrl     *gomock.Controller
	recorder *MockUALSvcClientMockRecorder
	isgomock struct{}
}

// MockUALSvcClientMockRecorder is the mock recorder for MockUALSvcClient.
type MockUALSvcClientMockRecorder struct {
	mock *MockUALSvcClient
}

// NewMockUALSvcClient creates a new mock instance.
func NewMockUALSvcClient(ctrl *gomock.Controller) *MockUALSvcClient {
	mock := &MockUALSvcClient{ctrl: ctrl}
	mock.recorder = &MockUALSvcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUALSvcClient) EXPECT() *MockUALSvcClientMockRecorder {
	return m.recorder
}

// UALDeviceDatapathReset mocks base method.
func (m *MockUALSvcClient) UALDeviceDatapathReset(ctx context.Context, in *amdgpu.UALDeviceDatapathResetRequest, opts ...grpc.CallOption) (*amdgpu.UALDeviceDatapathResetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALDeviceDatapathReset", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALDeviceDatapathResetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceDatapathReset indicates an expected call of UALDeviceDatapathReset.
func (mr *MockUALSvcClientMockRecorder) UALDeviceDatapathReset(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceDatapathReset", reflect.TypeOf((*MockUALSvcClient)(nil).UALDeviceDatapathReset), varargs...)
}

// UALDeviceGet mocks base method.
func (m *MockUALSvcClient) UALDeviceGet(ctx context.Context, in *amdgpu.UALDeviceGetRequest, opts ...grpc.CallOption) (*amdgpu.UALDeviceGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALDeviceGet", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALDeviceGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceGet indicates an expected call of UALDeviceGet.
func (mr *MockUALSvcClientMockRecorder) UALDeviceGet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceGet", reflect.TypeOf((*MockUALSvcClient)(nil).UALDeviceGet), varargs...)
}

// UALDeviceUpdate mocks base method.
func (m *MockUALSvcClient) UALDeviceUpdate(ctx context.Context, in *amdgpu.UALDeviceUpdateRequest, opts ...grpc.CallOption) (*amdgpu.UALDeviceUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALDeviceUpdate", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALDeviceUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceUpdate indicates an expected call of UALDeviceUpdate.
func (mr *MockUALSvcClientMockRecorder) UALDeviceUpdate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceUpdate", reflect.TypeOf((*MockUALSvcClient)(nil).UALDeviceUpdate), varargs...)
}

// UALNetworkPortGet mocks base method.
func (m *MockUALSvcClient) UALNetworkPortGet(ctx context.Context, in *amdgpu.UALNetworkPortGetRequest, opts ...grpc.CallOption) (*amdgpu.UALNetworkPortGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALNetworkPortGet", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALNetworkPortGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALNetworkPortGet indicates an expected call of UALNetworkPortGet.
func (mr *MockUALSvcClientMockRecorder) UALNetworkPortGet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALNetworkPortGet", reflect.TypeOf((*MockUALSvcClient)(nil).UALNetworkPortGet), varargs...)
}

// UALNetworkPortUpdate mocks base method.
func (m *MockUALSvcClient) UALNetworkPortUpdate(ctx context.Context, in *amdgpu.UALNetworkPortUpdateRequest, opts ...grpc.CallOption) (*amdgpu.UALNetworkPortUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALNetworkPortUpdate", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALNetworkPortUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALNetworkPortUpdate indicates an expected call of UALNetworkPortUpdate.
func (mr *MockUALSvcClientMockRecorder) UALNetworkPortUpdate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALNetworkPortUpdate", reflect.TypeOf((*MockUALSvcClient)(nil).UALNetworkPortUpdate), varargs...)
}

// UALStationGet mocks base method.
func (m *MockUALSvcClient) UALStationGet(ctx context.Context, in *amdgpu.UALStationGetRequest, opts ...grpc.CallOption) (*amdgpu.UALStationGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALStationGet", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALStationGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALStationGet indicates an expected call of UALStationGet.
func (mr *MockUALSvcClientMockRecorder) UALStationGet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALStationGet", reflect.TypeOf((*MockUALSvcClient)(nil).UALStationGet), varargs...)
}

// UALStationUpdate mocks base method.
func (m *MockUALSvcClient) UALStationUpdate(ctx context.Context, in *amdgpu.UALStationUpdateRequest, opts ...grpc.CallOption) (*amdgpu.UALStationUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UALStationUpdate", varargs...)
	ret0, _ := ret[0].(*amdgpu.UALStationUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALStationUpdate indicates an expected call of UALStationUpdate.
func (mr *MockUALSvcClientMockRecorder) UALStationUpdate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALStationUpdate", reflect.TypeOf((*MockUALSvcClient)(nil).UALStationUpdate), varargs...)
}

// MockUALSvcServer is a mock of UALSvcServer interface.
type MockUALSvcServer struct {
	ctrl     *gomock.Controller
	recorder *MockUALSvcServerMockRecorder
	isgomock struct{}
}

// MockUALSvcServerMockRecorder is the mock recorder for MockUALSvcServer.
type MockUALSvcServerMockRecorder struct {
	mock *MockUALSvcServer
}

// NewMockUALSvcServer creates a new mock instance.
func NewMockUALSvcServer(ctrl *gomock.Controller) *MockUALSvcServer {
	mock := &MockUALSvcServer{ctrl: ctrl}
	mock.recorder = &MockUALSvcServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUALSvcServer) EXPECT() *MockUALSvcServerMockRecorder {
	return m.recorder
}

// UALDeviceDatapathReset mocks base method.
func (m *MockUALSvcServer) UALDeviceDatapathReset(arg0 context.Context, arg1 *amdgpu.UALDeviceDatapathResetRequest) (*amdgpu.UALDeviceDatapathResetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALDeviceDatapathReset", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALDeviceDatapathResetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceDatapathReset indicates an expected call of UALDeviceDatapathReset.
func (mr *MockUALSvcServerMockRecorder) UALDeviceDatapathReset(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceDatapathReset", reflect.TypeOf((*MockUALSvcServer)(nil).UALDeviceDatapathReset), arg0, arg1)
}

// UALDeviceGet mocks base method.
func (m *MockUALSvcServer) UALDeviceGet(arg0 context.Context, arg1 *amdgpu.UALDeviceGetRequest) (*amdgpu.UALDeviceGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALDeviceGet", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALDeviceGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceGet indicates an expected call of UALDeviceGet.
func (mr *MockUALSvcServerMockRecorder) UALDeviceGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceGet", reflect.TypeOf((*MockUALSvcServer)(nil).UALDeviceGet), arg0, arg1)
}

// UALDeviceUpdate mocks base method.
func (m *MockUALSvcServer) UALDeviceUpdate(arg0 context.Context, arg1 *amdgpu.UALDeviceUpdateRequest) (*amdgpu.UALDeviceUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALDeviceUpdate", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALDeviceUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALDeviceUpdate indicates an expected call of UALDeviceUpdate.
func (mr *MockUALSvcServerMockRecorder) UALDeviceUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALDeviceUpdate", reflect.TypeOf((*MockUALSvcServer)(nil).UALDeviceUpdate), arg0, arg1)
}

// UALNetworkPortGet mocks base method.
func (m *MockUALSvcServer) UALNetworkPortGet(arg0 context.Context, arg1 *amdgpu.UALNetworkPortGetRequest) (*amdgpu.UALNetworkPortGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALNetworkPortGet", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALNetworkPortGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALNetworkPortGet indicates an expected call of UALNetworkPortGet.
func (mr *MockUALSvcServerMockRecorder) UALNetworkPortGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALNetworkPortGet", reflect.TypeOf((*MockUALSvcServer)(nil).UALNetworkPortGet), arg0, arg1)
}

// UALNetworkPortUpdate mocks base method.
func (m *MockUALSvcServer) UALNetworkPortUpdate(arg0 context.Context, arg1 *amdgpu.UALNetworkPortUpdateRequest) (*amdgpu.UALNetworkPortUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALNetworkPortUpdate", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALNetworkPortUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALNetworkPortUpdate indicates an expected call of UALNetworkPortUpdate.
func (mr *MockUALSvcServerMockRecorder) UALNetworkPortUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALNetworkPortUpdate", reflect.TypeOf((*MockUALSvcServer)(nil).UALNetworkPortUpdate), arg0, arg1)
}

// UALStationGet mocks base method.
func (m *MockUALSvcServer) UALStationGet(arg0 context.Context, arg1 *amdgpu.UALStationGetRequest) (*amdgpu.UALStationGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALStationGet", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALStationGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALStationGet indicates an expected call of UALStationGet.
func (mr *MockUALSvcServerMockRecorder) UALStationGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALStationGet", reflect.TypeOf((*MockUALSvcServer)(nil).UALStationGet), arg0, arg1)
}

// UALStationUpdate mocks base method.
func (m *MockUALSvcServer) UALStationUpdate(arg0 context.Context, arg1 *amdgpu.UALStationUpdateRequest) (*amdgpu.UALStationUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UALStationUpdate", arg0, arg1)
	ret0, _ := ret[0].(*amdgpu.UALStationUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UALStationUpdate indicates an expected call of UALStationUpdate.
func (mr *MockUALSvcServerMockRecorder) UALStationUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UALStationUpdate", reflect.TypeOf((*MockUALSvcServer)(nil).UALStationUpdate), arg0, arg1)
}

// mustEmbedUnimplementedUALSvcServer mocks base method.
func (m *MockUALSvcServer) mustEmbedUnimplementedUALSvcServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedUALSvcServer")
}

// mustEmbedUnimplementedUALSvcServer indicates an expected call of mustEmbedUnimplementedUALSvcServer.
func (mr *MockUALSvcServerMockRecorder) mustEmbedUnimplementedUALSvcServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedUALSvcServer", reflect.TypeOf((*MockUALSvcServer)(nil).mustEmbedUnimplementedUALSvcServer))
}

// MockUnsafeUALSvcServer is a mock of UnsafeUALSvcServer interface.
type MockUnsafeUALSvcServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeUALSvcServerMockRecorder
	isgomock struct{}
}

// MockUnsafeUALSvcServerMockRecorder is the mock recorder for MockUnsafeUALSvcServer.
type MockUnsafeUALSvcServerMockRecorder struct {
	mock *MockUnsafeUALSvcServer
}

// NewMockUnsafeUALSvcServer creates a new mock instance.
func NewMockUnsafeUALSvcServer(ctrl *gomock.Controller) *MockUnsafeUALSvcServer {
	mock := &MockUnsafeUALSvcServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeUALSvcServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeUALSvcServer) EXPECT() *MockUnsafeUALSvcServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedUALSvcServer mocks base method.
func (m *MockUnsafeUALSvcServer) mustEmbedUnimplementedUALSvcServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedUALSvcServer")
}

// mustEmbedUnimplementedUALSvcServer indicates an expected call of mustEmbedUnimplementedUALSvcServer.
func (mr *MockUnsafeUALSvcServerMockRecorder) mustEmbedUnimplementedUALSvcServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedUALSvcServer", reflect.TypeOf((*MockUnsafeUALSvcServer)(nil).mustEmbedUnimplementedUALSvcServer))
}
