{
 "title": "Overview",
 "description": "Overview of the system",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_gpu_uuids", "query": { "query": "label_values(GPU_UUID)" } },
   { "name": "g_job_ids", "query": { "query": "label_values(job_id)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU Nodes",
   "type": "stat",
   "description": "Number of nodes with GPUs",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gpu_nodes_total)", "legendFormat": "GPU nodes" }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total power usage, in Watts",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gpu_power_usage)", "legendFormat": "Power Usage (W)" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Estimated maximum PCIe bandwidth over the last second, in MB/s",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcie_max_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PCIe Recovery Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_recovery_count)", "legendFormat": "PCIe Recovery Count" }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(5, gpu_used_vram)", "legendFormat": "{{GPU_UUID}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gpu_used_vram)", "legendFormat": "__auto" },
    { "expr": "sum(gpu_total_vram)", "legendFormat": "__auto" },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "PCIe Replay Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_replay_count)", "legendFormat": "Replay" },
    {
     "expr": "sum(pcie_replay_rollover_count)",
     "legendFormat": "Replay Rollover"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(job_id) (gpu_nodes_total{job_id!=\"\"}))",
     "legendFormat": "Jobs"
    }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "stat",
   "description": "Total current PCIe bandwidth, in MB/s",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_bandwidth)", "legendFormat": "PCIe Bandwidth" }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by() (5, gpu_gfx_activity)",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Total accumulated energy consumed",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_energy_consumed)",
     "legendFormat": "Accumulated Energy Consumed (nJ)"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "PCIe NACK Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pcie_nack_received_count)", "legendFormat": "Received" },
    { "expr": "sum(pcie_nack_sent_count)", "legendFormat": "Sent" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg(gpu_gfx_activity)", "legendFormat": "GPU Usage" }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gpu_package_power)", "legendFormat": "GPU Power" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Current edge temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(gpu_edge_temperature)", "legendFormat": "GPU Temperature" }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(gpu_memory_temperature)", "legendFormat": "Memory Temperature" }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "avg(gpu_hbm_temperature)", "legendFormat": "HBM Temperature" },
    { "expr": "avg(gpu_edge_temperature)", "legendFormat": "Edge Temperature" },
    { "expr": "avg(gpu_junction_temperature)", "legendFormat": "Junction Temperature" }
   ]
  }
 ]
}