{
 "title": "GPU",
 "description": "View by GPU",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_gpu_uuid", "label": "GPU UUID", "query": { "query": "label_values(GPU_UUID)" } },
   {
    "name": "g_card_series",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},CARD_SERIES)"
    }
   },
   {
    "name": "g_gpu_id",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},GPU_ID)"
    }
   },
   {
    "name": "g_gpu_vbios",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},VBIOS_VERSION)"
    }
   },
   {
    "name": "g_driver",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},DRIVER_VERSION)"
    }
   },
   {
    "name": "g_instance",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},instance)"
    }
   },
   {
    "name": "g_card_vendor",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},CARD_VENDOR)"
    }
   },
   {
    "name": "g_card_model",
    "query": {
     "query": "label_values({GPU_UUID=\"$g_gpu_uuid\"},CARD_MODEL)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device",
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "${g_card_vendor}\n\n#### SERIES\n${g_card_series}\n\n#### MODEL\n${g_card_model}"
   },
   "targets": [
    { "expr": "$g_card_series", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Software",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": {
    "content": "#### VBIOS\n${g_gpu_vbios}\n\n#### DRIVER\n${g_driver}"
   }
  },
  {
   "title": "GPU Package Power",
   "type": "gauge",
   "description": "GPU current power",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_package_power{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "estimated maximum PCIe bandwidth over the last second in MB/s",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_max_speed{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "PCIe Recovery Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_recovery_count{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Accumulated energy consumed",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_energy_consumed{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "stat",
   "description": "% used VRAM of the GPU",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_used_vram{GPU_UUID=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gpu_total_vram{GPU_UUID=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "PCIe Bandwidth",
   "type": "stat",
   "description": "estimated maximum PCIe bandwidth over the last second in MB/s",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_bandwidth{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "PCIe Replay Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_replay_count{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Replay"
    },
    {
     "expr": "pcie_replay_rollover_count{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Replay Rollover"
    }
   ]
  },
  {
   "title": "PCIe NACK Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_nack_received_count{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "pcie_nack_sent_count{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "GPU ID", "type": "text", "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 }, "options": { "content": "${g_gpu_id}" } },
  { "title": "GPU UUID", "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 }, "options": { "content": "${g_gpu_uuid}" } },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "description": "Current GFX activity",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_gfx_activity{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM on the GPU over time, in MB",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "downsampler": "mean", "expression": "($A / $B) * 100", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "description": "GPU package power, in Watts",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_package_power{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Current edge temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_edge_temperature{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_memory_temperature{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "{{GPU_UUID}}"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "description": "Current temperatures, in celsius:\n- 4 HBM temperatures\n- Edge temperature\n- Junction/hotspot temperature",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_hbm_temperature{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "HBM - {{hbm_index}}"
    },
    {
     "expr": "gpu_edge_temperature{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "gpu_junction_temperature{GPU_UUID=\"$g_gpu_uuid\"}",
     "legendFormat": "Junction Temperature"
    }
   ]
  }
 ]
}