{
 "title": "Demo Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "GPU Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_nodes_total{instance=\"10.30.60.190:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_total_memory{instance=\"10.30.60.190:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GPU HBM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg(gpu_hbm_temperature{instance=\"10.30.60.190:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Junction Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "avg(gpu_junction_temperature{instance=\"10.30.60.190:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Edge Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg(gpu_edge_temperature{instance=\"10.30.60.190:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "gpu_memory_usage{instance=\"10.30.60.190:5000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Average Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "avg(gpu_power_usage{instance=\"10.30.60.190:5000\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "gpu_usage{instance=\"10.30.60.190:5000\"}",
     "legendFormat": "{{usage}}"
    }
   ]
  }
 ]
}