global:
  scrape_interval: 10s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 10s
runtime:
  gogc: 75
scrape_configs:
- job_name: rdc
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 10s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+):\d+
    target_label: short_instance
    replacement: $1
    action: replace
  file_sd_configs:
  - files:
    - /etc/prometheus/prometheus_targets.json
    refresh_interval: 5m
  static_configs:
  - targets:
    - localhost:5000

