---
version: 2.0
builds:
  build-device-metrics-exporter:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-metrics-exporter && make all"]
    owners: ["email:prshanmug@amd.com"]
    artifacts:
        - /device-metrics-exporter/bin/amd-metrics-exporter
  
  build-device-metrics-exporter-docker:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-metrics-exporter && make docker"]
    owners: ["email:prshanmug@amd.com"]
    artifacts:
        - /device-metrics-exporter/docker/obj/exporter-release-v1.tgz

  build-device-metrics-exporter-docker-mock:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/device-metrics-exporter && make docker-mock"]
    owners: ["email:prshanmug@amd.com"]
    artifacts:
        - /device-metrics-exporter/docker/obj/exporter-release-v1.tgz

targets:
  api-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/device-metrics-exporter && \
                                    make checks"]
    owners: ["email:prshanmug@amd.com"]
    area:
    sub-area:
    feature:

  device-metrics-unit-test:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/device-metrics-exporter && \
                                    make checks && \
                                    make unit-test"]
    owners: ["email:prshanmug@amd.com"]
    area:
    sub-area:
    feature:
    logfiles:
        - /device-metrics-exporter/internal/amdgpu/gpuagent/exporter_ut.logexporter.log

image:
  bind_dir: "/device-metrics-exporter"
  work_dir: "/device-metrics-exporter"

jobs:
  asset-build:
    labels: ["CI-Sanity-Build"]

