platform: k8s

# -- Add node selector for the daemonset of metrics exporter
nodeSelector: {}

# -- Add tolerations for deploying metrics exporter on tainted nodes
tolerations: []

image:
  # -- repository URL for the metrics exporter image
  repository: docker.io/rocm/device-metrics-exporter
  # -- metrics exporter image tag
  tag: v1.3.0
  # -- metrics exporter image pullPolicy
  pullPolicy: Always
  # -- metrics exporter image pullSecret name
  pullSecrets: ""
  # -- metrics exporter initContainer image
  initContainerImage: busybox:1.36

service:
  # -- metrics exporter service type, could be ClusterIP or NodePort
  type: ClusterIP
  ClusterIP:
    # -- set port for ClusterIP type service
    port: 5000
  NodePort:
    # -- set port for NodePort type service   
    port: 5000
    # -- set nodePort for NodePort type service  
    nodePort: 32500

# -- configMap name for the customizing configs and mount into metrics exporter container
configMap: ""

# -- ServiceMonitor configuration
serviceMonitor:
  # -- Whether to create a ServiceMonitor resource for Prometheus Operator
  enabled: false
  # -- Scrape interval for the ServiceMonitor
  interval: "30s"
  # -- Honor labels configuration for ServiceMonitor
  honorLabels: true
  # -- Honor timestamps configuration for ServiceMonitor
  honorTimestamps: true
  # -- Adds node metadata to discovered targets for node-based filtering
  attachMetadata:
    node: false
  # -- Additional labels for the ServiceMonitor
  labels: {}
  # -- RelabelConfigs to apply to samples before scraping
  relabelings: []
  # -- Relabeling rules applied to individual scraped metrics
  metricRelabelings: []

