platform: k8s

# -- Add node selector for the daemonset of metrics exporter
nodeSelector: {}

image:
  # -- repository URL for the metrics exporter image
  repository: docker.io/rocm/device-metrics-exporter
  # -- metrics exporter image tag
  tag: v1.2.0
  # -- metrics exporter image pullPolicy
  pullPolicy: Always
  # -- metrics exporter image pullSecret name
  pullSecrets: ""
  # -- metrics exporter initContainer image
  initContainerImage: busybox:1.36

service:
  # -- metrics exporter service type, could be ClusterIP or NodePort
  type: ClusterIP
  ClusterIP:
    # -- set port for ClusterIP type service
    port: 5000
  NodePort:
    # -- set port for NodePort type service   
    port: 5000
    # -- set nodePort for NodePort type service  
    nodePort: 32500

# -- configMap name for the customizing configs and mount into metrics exporter container
configMap: ""

