{
 "title": "GPU",
 "description": "View by GPU",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_gpu_uuid", "label": "GPU UUID", "query": { "query": "label_values(gpu_uuid)" } },
   {
    "name": "g_card_series",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_series)"
    }
   },
   {
    "name": "g_gpu_id",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},gpu_id)"
    }
   },
   {
    "name": "g_gpu_vbios",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},vbios_version)"
    }
   },
   {
    "name": "g_driver",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},driver_version)"
    }
   },
   {
    "name": "g_card_vendor",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_vendor)"
    }
   },
   {
    "name": "g_card_model",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_model)"
    }
   },
   {
    "name": "g_hostname",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},hostname)"
    }
   },
   {
    "name": "g_serial_number",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},serial_number)"
    }
   },
   { "name": "g_mi300_model", "label": "MI300 Model", "query": "${VAR_G_MI300_MODEL}" }
  ]
 },
 "panels": [
  {
   "title": "Device",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "#### VENDOR\n${g_card_vendor}\n\n#### SERIES\n${g_card_series}\n\n#### MODEL\n${g_card_model}\n\n#### SERIAL\n${g_serial_number}"
   },
   "targets": [
    { "expr": "$g_card_series", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": {
    "content": "#### HOST\n${g_hostname}\n\n#### GPU ID\n${g_gpu_id}"
   }
  },
  {
   "title": "GPU Package Power",
   "type": "gauge",
   "description": "GPU current power",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_package_power{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "estimated maximum PCIe bandwidth over the last second in MB/s",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_max_speed{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_recovery_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "Recovery"
    },
    {
     "expr": "pcie_replay_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "Replay"
    },
    {
     "expr": "pcie_replay_rollover_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "pcie_nack_received_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "pcie_nack_sent_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Total Correctable ECC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_ecc_correct_total{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "Total Correctable ECC"
    }
   ]
  },
  {
   "title": "PCIe Bandwidth",
   "type": "timeseries",
   "description": "Current PCIe bandwidth",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "pcie_bandwidth{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "stat",
   "description": "% used VRAM of the GPU",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_used_vram{gpu_uuid=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gpu_total_vram{gpu_uuid=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Software",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": {
    "content": "#### VBIOS\n${g_gpu_vbios}\n\n#### DRIVER\n${g_driver}"
   }
  },
  {
   "title": "PCIe Bandwidth",
   "type": "stat",
   "description": "estimated maximum PCIe bandwidth over the last second in MB/s",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pcie_bandwidth{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "title": "Total Uncorrectable ECC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_ecc_uncorrect_total{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "Total Uncorrectable ECC"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Accumulated energy consumed",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "description": "Current GFX activity",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_gfx_activity{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM on the GPU over time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "downsampler": "mean", "expression": "($A / $B) * 100", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "description": "GPU package power, in Watts",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_package_power{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Current GPU temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_edge_temperature{gpu_uuid=\"$g_gpu_uuid\", card_model!=\"$g_mi300_model\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_junction_temperature{gpu_uuid=\"$g_gpu_uuid\", card_model=\"$g_mi300_model\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_memory_temperature{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "description": "Current temperatures, in Celsius:\n- 4 HBM temperatures\n- Edge temperature\n- Junction/hotspot temperature",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_hbm_temperature{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "HBM - {{hbm_index}}"
    },
    {
     "expr": "gpu_edge_temperature{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "gpu_junction_temperature{gpu_uuid=\"$g_gpu_uuid\"}",
     "legendFormat": "Junction Temperature"
    }
   ]
  }
 ]
}