{
 "title": "System",
 "tags": [ "version: 1.4.1" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_metrics_prefix", "label": "Metrics Prefix" },
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "g_hostname",
    "label": "Compute Node",
    "query": {
     "query": "label_values({cluster_name=~\"$g_cluster_name\"},hostname)"
    }
   },
   {
    "name": "g_gpu_id",
    "label": "GPU ID",
    "query": {
     "query": "label_values({hostname=~\"$g_hostname\"},gpu_id)"
    }
   },
   {
    "name": "g_gpu_partition_id",
    "label": "Partition",
    "query": {
     "query": "label_values({hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"},gpu_partition_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPUs",
   "type": "stat",
   "description": "Number of GPUs on the compute node",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_activity\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "# of GPUs"
    },
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_busy_instantaneous\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "# of GPUs"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs running on this compute node",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_activity{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_activity{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs (Pods)"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs (Pods)"
    }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "\\# of GPUs allocated by jobs",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_activity\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_busy_instantaneous\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_activity\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_id) ({\"${g_metrics_prefix}gpu_gfx_busy_instantaneous\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_activity{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    },
    {
     "expr": "sum(group by(gpu_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    },
    {
     "expr": "count(${g_metrics_prefix}gpu_health{hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"} < 1)",
     "legendFormat": "Unhealthy GPUs"
    }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"${g_metrics_prefix}pcie_max_speed\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta({\"${g_metrics_prefix}pcie_recovery_count\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta({\"${g_metrics_prefix}pcie_replay_count\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta({\"${g_metrics_prefix}pcie_replay_rollover_count\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta({\"${g_metrics_prefix}pcie_nack_received_count\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta({\"${g_metrics_prefix}pcie_nack_sent_count\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Top 5 Jobs by GPU Usage",
   "type": "stat",
   "description": "Top 5 jobs by GPU usage across selected compute nodes, listed by the index of the GPU the job is running on and the pod/job ID",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, {\"${g_metrics_prefix}gpu_gfx_activity\", hostname=~\"$g_hostname\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "[GPU: {{gpu_id}}] {{pod}}{{job_id}}"
    },
    {
     "expr": "topk(5, {\"${g_metrics_prefix}gpu_gfx_busy_instantaneous\", hostname=~\"$g_hostname\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "[GPU: {{gpu_id}}] {{pod}}{{job_id}}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs across selected compute nodes with highest VRAM used, labeled with GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, {\"${g_metrics_prefix}gpu_used_vram\", hostname=~\"$g_hostname\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total package power usage, in Watts",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Total Current PCIe Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"${g_metrics_prefix}pcie_bandwidth\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "Total current PCIe bandwidth"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "PCIe bandwidth in Mb/s",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum({\"${g_metrics_prefix}pcie_bandwidth\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ECC Counts",
   "type": "stat",
   "description": "Total ECC counts across all GPUs in this compute node",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta({\"${g_metrics_prefix}gpu_ecc_correct_total\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "Correctable"
    },
    {
     "expr": "sum(delta({\"${g_metrics_prefix}gpu_ecc_uncorrect_total\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"}[$__interval]))",
     "legendFormat": "Uncorrectable"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current CPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_gfx_activity\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_gfx_busy_instantaneous\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_package_power\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_average_package_power\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Current temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_edge_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_junction_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_memory_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_hbm_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_edge_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg({\"${g_metrics_prefix}gpu_junction_temperature\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\", gpu_partition_id=~\"$g_gpu_partition_id\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs in selected compute nodes. Click on the GPU ID values to filter dashboard.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{\"${g_metrics_prefix}gpu_health\", hostname=~\"$g_hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "SM Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_sm_active{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_sm_active{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Occupancy / Compute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_cu{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_cu{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "SIMD Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_simd_utilization{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_simd_utilization{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Tensor Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_tensor_active_percent{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_tensor_active_percent{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "Occupancy / Active Compute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_active_cu{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_occupancy_per_active_cu{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    },
    {
     "title": "GUI Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "${g_metrics_prefix}gpu_prof_gui_util_percent{pod!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      },
      {
       "expr": "${g_metrics_prefix}gpu_prof_gui_util_percent{job_id!=\"\", hostname=~\"$g_hostname\", gpu_id=~\"$g_gpu_id\"}",
       "legendFormat": "GPU: {{gpu_id}} - Job: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}