ARG BASE_IMAGE=ubuntu:22.04

FROM ${BASE_IMAGE}

LABEL maintainer="AMD Inc"
LABEL OS="ubuntu:22.04"

RUN apt update && \
   apt install -y sudo findutils procps file tar jq iproute2 ethtool libatomic1 && \
   apt clean && rm -rf /var/lib/apt/lists/*

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/amd/bin/:/opt/rocm/bin/:/opt/nic/bin:/opt/nic/sbin
ENV LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH
ENV SIM_ENABLE=1
RUN mkdir -p /home/amd/bin/ /home/amd/tools/ /mockdata

ADD ./rocpctl-mock /home/amd/bin/rocpctl
ADD ./gpuctl ./gpuagent ./metricsclient ./amdgpuhealth /home/amd/bin/
ADD ./amd-metrics-exporter /home/amd/bin/server
ADD ./entrypoint.sh /home/amd/tools/entrypoint.sh
ADD ./LICENSE /licenses/LICENSE
RUN chmod +x /home/amd/tools/entrypoint.sh

COPY ./mockdata /mockdata

LABEL name="amd-device-metrics-exporter-mock" \ 
    maintainer="praveenkumar.shanmugam@amd.com,nitish.bhat@amd.com,yan.sun3@amd.com,shrey.ajmera@amd.com" \
    vendor="Advanced Micro Devices, Inc." \
    version="v1.5.0" \
    release="v1.5.0" \
    summary="Mock AMD Device Metrics Exporter is used for mocking Device Metrics Exporter behaviour on non-GPU nodes." \
    description="Mock AMD Device Metrics Exporter is used for mocking Device Metrics Exporter behaviour on non-GPU nodes. Used for e2e testing on non-GPU nodes."

ENTRYPOINT ["/home/amd/tools/entrypoint.sh"]
