---
version: 2.0
targets:
  copy-device-metrics-exporter-artifacts:
    commands: ["sh", "-c", "pwd && cd ./asset-build && ./exporter-asset-push.sh"]
    owners: ["email:prshanmug@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
      - build-debian-package
      - build-device-metrics-exporter-docker
      - e2e-test-mock-exporter

image:
  bind_dir: "/go/src/github.com/pensando/device-metrics-exporter"
  work_dir: "/go/src/github.com/pensando/device-metrics-exporter"
