---
version: 2.0
targets:
  copy-device-metrics-exporter-artifacts:
    commands: ["sh", "-c", "pwd && cd ./asset-build && ./exporter-asset-push.sh"]
    owners: ["email:prshanmug@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
      - build-debian-package-ub22.04
      - build-debian-package-ub24.04
      - build-device-metrics-exporter-docker-ubi9.4
      - build-device-metrics-exporter-docker-azure
      - build-helm-artifact
      - e2e-build-mock-exporter
  copy-test-runner-artifacts:
    commands: ["sh", "-c", "pwd && cd ./asset-build && ./test-runner-asset-push.sh"]
    owners: ["email:yan.sun3@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
      - build-test-runner-docker

image:
  bind_dir: "/go/src/github.com/ROCm/device-metrics-exporter"
  work_dir: "/go/src/github.com/ROCm/device-metrics-exporter"
