apiVersion: v1
kind: ServiceAccount
metadata:
  name: amdgpu-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-exporter.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-charts-exporter.fullname" . }}-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - get
  - list
  - update
{{- if eq .Values.platform "openshift" }}
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-charts-exporter.fullname" . }}-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm-charts-exporter.fullname" . }}-metrics-exporter'
subjects:
- kind: ServiceAccount
  name: amdgpu-metrics-exporter
  namespace: '{{ .Release.Namespace }}'