apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amd-metrics-exporter-svc
spec:
  selector:
    app: {{ .Release.Name }}-amdgpu-metrics-exporter
  internalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: Local
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.NodePort.port }}
      nodePort: {{ .Values.service.NodePort.nodePort }}
  {{- end }}
  {{- if eq .Values.service.type "ClusterIP" }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.ClusterIP.port }}
  {{- end }}