ignores:
  - CHANGELOG.md
  - "**/vendor/**"
  - "**/.git/**"
  - "**/tests/e2e/**"
  - "**/helm-charts-k8s/README.md"
  - "**/internal/**"
  - "**/CLAUDE.md"
  - "**/.claude/**"
  - "**/libamdsmi/**"
  - "**/libgimsmi/**"
  - "**/gpuagent/**"
  - "**/tools/**"
  - "**/README.md"
